name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Ensure that the action is triggered when code is pushed to the master branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker Image
      run: |
        docker build -t yourdockerhubusername/your-image-name:latest .  # Adjust the name accordingly

    - name: Push Docker Image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push yourdockerhubusername/your-image-name:latest  # Adjust with your DockerHub username/image name

