name: Build and Push VPP Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu_version: [20.04, 22.04, 24.04] # Different Ubuntu versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: my-dockerhub-username/vpp:${{ matrix.ubuntu_version }}
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
